require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PresidentsController do

  # This should return the minimal set of attributes required to create a valid
  # President. As you add validations to President, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PresidentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all presidents as @presidents" do
      president = President.create! valid_attributes
      get :index, {}, valid_session
      assigns(:presidents).should eq([president])
    end
  end

  describe "GET show" do
    it "assigns the requested president as @president" do
      president = President.create! valid_attributes
      get :show, {:id => president.to_param}, valid_session
      assigns(:president).should eq(president)
    end
  end

  describe "GET new" do
    it "assigns a new president as @president" do
      get :new, {}, valid_session
      assigns(:president).should be_a_new(President)
    end
  end

  describe "GET edit" do
    it "assigns the requested president as @president" do
      president = President.create! valid_attributes
      get :edit, {:id => president.to_param}, valid_session
      assigns(:president).should eq(president)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new President" do
        expect {
          post :create, {:president => valid_attributes}, valid_session
        }.to change(President, :count).by(1)
      end

      it "assigns a newly created president as @president" do
        post :create, {:president => valid_attributes}, valid_session
        assigns(:president).should be_a(President)
        assigns(:president).should be_persisted
      end

      it "redirects to the created president" do
        post :create, {:president => valid_attributes}, valid_session
        response.should redirect_to(President.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved president as @president" do
        # Trigger the behavior that occurs when invalid params are submitted
        President.any_instance.stub(:save).and_return(false)
        post :create, {:president => {  }}, valid_session
        assigns(:president).should be_a_new(President)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        President.any_instance.stub(:save).and_return(false)
        post :create, {:president => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested president" do
        president = President.create! valid_attributes
        # Assuming there are no other presidents in the database, this
        # specifies that the President created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        President.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => president.to_param, :president => { "these" => "params" }}, valid_session
      end

      it "assigns the requested president as @president" do
        president = President.create! valid_attributes
        put :update, {:id => president.to_param, :president => valid_attributes}, valid_session
        assigns(:president).should eq(president)
      end

      it "redirects to the president" do
        president = President.create! valid_attributes
        put :update, {:id => president.to_param, :president => valid_attributes}, valid_session
        response.should redirect_to(president)
      end
    end

    describe "with invalid params" do
      it "assigns the president as @president" do
        president = President.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        President.any_instance.stub(:save).and_return(false)
        put :update, {:id => president.to_param, :president => {  }}, valid_session
        assigns(:president).should eq(president)
      end

      it "re-renders the 'edit' template" do
        president = President.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        President.any_instance.stub(:save).and_return(false)
        put :update, {:id => president.to_param, :president => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested president" do
      president = President.create! valid_attributes
      expect {
        delete :destroy, {:id => president.to_param}, valid_session
      }.to change(President, :count).by(-1)
    end

    it "redirects to the presidents list" do
      president = President.create! valid_attributes
      delete :destroy, {:id => president.to_param}, valid_session
      response.should redirect_to(presidents_url)
    end
  end

end
